name: Bump lychee version

on: push

jobs:
  bumpLycheeVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Bump lychee version
        run: ./bump-lychee.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
